export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";
export const RESET_SEARCH_FIELD = "RESET_SEARCH_FIELD";
export const IS_INPUT_EMPTY = "IS_INPUT_EMPTY";

export const FETCH_RECIPES_PENDING = "FETCH_RECIPES_PENDING";
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS";
export const FETCH_RECIPES_FAILED = "FETCH_RECIPES_FAILED";

export const FETCH_DETAIL_PENDING = "FETCH_RDETAIL_PENDING";
export const FETCH_DETAIL_SUCCESS = "FETCH_DETAIL_SUCCESS";
export const FETCH_DETAIL_FAILED = "FETCH_DETAIL_FAILED";

export const ADD_LIKE = "ADD_LIKE";
export const DELETE_LIKE = "DELETE_LIKE";
export const RESET_LIKE = "RESET_LIKE";
export const HANDLE_MODAL = "HANDLE_MODAL";
export const HANDLE_CONFIRM = "HANDLE_CONFIRM";

export const CHANGE_PAGINATION_PAGE = "CHANGE_PAGINATION_PAGE";
